#!/usr/bin/env bash

filename=$HOME/data/strange-coop-logs/strange-coop
ext=log
if [[ -e $filename.$ext ]] ; then
  i=0
  while [[ -e $filename-$i.$ext ]] ; do
    let i++
  done
  filename=$filename-$i
fi
filename=$filename.$ext
echo "Writing to filename: $filename"

lein trampoline run -m strange-coop.core > $filename

